name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag hello-rust:latest
        
        docker run --rm hello-rust:latest echo "User: "
        docker run --rm hello-rust:latest whoami
        
        docker run --rm hello-rust:latest echo "Location: "
        docker run --rm hello-rust:latest pwd
        
        
        docker run --rm hello-rust:latest bash -c 'cat "127.0.0.1 index.crates.io" >> /etc/hosts'
        docker run --rm hello-rust:latest bash -c 'cat "127.0.0.1 static.crates.io" >> /etc/hosts'
        docker run --rm hello-rust:latest echo "Override /etc/hosts"
        docker run --rm hello-rust:latest cat /etc/hosts
        
        docker run --rm hello-rust:latest cargo build
