name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag hello-rust:latest
        docker run --rm hello-rust:latest cat /build/hosts >> /etc/hosts
        docker run --rm hello-rust:latest cargo build
